#!/bin/bash
echo "=== DEPLOYMENT DIAGNOSTIC ==="
echo ""
echo "1. Build files:"
ls -lh dist/index.js 2>/dev/null || echo "  ❌ dist/index.js not found"
ls -lh dist/public/index.html 2>/dev/null || echo "  ❌ dist/public/index.html not found"
echo ""
echo "2. .replit file (deployment section):"
grep -A 5 "\[deployment\]" .replit
echo ""
echo "3. Package.json scripts:"
grep -A 3 '"scripts"' package.json
echo ""
echo "4. Test production server locally:"
timeout 3 node dist/index.js > /dev/null 2>&1 && echo "  ✅ Server starts successfully" || echo "  ⚠️ Server has issues"
echo ""
echo "=== NEXT STEPS ==="
echo "1. Copy this .replit configuration and paste it into your .replit file"
echo "2. In Deployments panel: Delete current deployment"
echo "3. Create NEW Reserved VM deployment"
echo "4. Make sure these environment variables are set in deployment:"
echo "   - DATABASE_URL"
echo "   - ZOHO_CLIENT_ID"
echo "   - ZOHO_CLIENT_SECRET"
echo "   - ZOHO_ORG_ID"
