import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'fr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation data
const translations = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.resources': 'Resources',
    'nav.directory': 'Directory',
    'nav.community': 'Community',
    'nav.contact': 'Contact',
    'nav.getHelp': 'Get Help',
    
    // Hero Section
    'hero.badge': 'Clinical Excellence Platform',
    'hero.title.canadian': 'Canadian',
    'hero.title.amyloidosis': 'Amyloidosis',
    'hero.title.society': 'Society',
    'hero.subtitle': 'Advancing evidence-based amyloidosis care through clinical excellence, professional collaboration, and structured knowledge sharing.',
    'hero.getStarted': 'Get Started',
    'hero.learnMore': 'Learn More',
    
    // Welcome Section
    'welcome.badge': 'Who we are',
    'welcome.title.welcome': 'Welcome to the',
    'welcome.title.cas': 'Canadian Amyloidosis Society',
    'welcome.subtitle': 'Your trusted partner in amyloidosis care, connecting patients, families, and healthcare professionals across Canada.',
    'welcome.description': 'We are dedicated to improving the lives of those affected by amyloidosis through education, support, and advocacy. Our comprehensive platform provides essential resources, connects you with specialized care, and builds a supportive community for patients and families nationwide.',
    'welcome.mission': 'Our Mission',
    'welcome.missionText': 'To accelerate awareness, improve diagnosis, and enhance care for amyloidosis patients across Canada through education, advocacy, and community support.',
    'welcome.vision': 'Our Vision',
    'welcome.visionText': 'A future where every Canadian affected by amyloidosis receives timely diagnosis, optimal treatment, and comprehensive support.',
    'welcome.exploreResources': 'Learn More About Our Work',
    
    // About Amyloidosis Section
    'about.badge': 'Medical Information',
    'about.title.what': 'What is',
    'about.title.amyloidosis': 'Amyloidosis',
    'about.subtitle': 'Amyloidosis is a rare disease with life-altering consequences—but early detection can dramatically improve outcomes. The Canadian Amyloidosis Society is building a trusted national hub for clinicians, researchers, and families seeking answers.',
    'about.description': 'Amyloidosis is a rare but serious condition where misfolded proteins (amyloid) accumulate in organs and tissues throughout the body. Understanding the different types, recognizing early symptoms, and accessing specialized care are crucial for managing this condition effectively.',
    'about.earlyDetection': 'Early Detection Saves Lives',
    'about.earlyDetectionText': 'Recognizing symptoms early and getting proper diagnosis can significantly improve treatment outcomes and quality of life.',
    'about.earlyDetection.title': 'Early Detection',
    'about.earlyDetection.subtitle': 'Saves Lives',
    'about.earlyDetection.description': 'Amyloidosis is often misdiagnosed or diagnosed late because its symptoms mimic other conditions. Early recognition and proper testing are crucial for better patient outcomes.',
    'about.earlyDetection.subdescription': 'Our directory connects patients with specialized centers and healthcare providers experienced in diagnosing and treating amyloidosis across Canada.',
    'about.learnMore': 'Learn More',
    'about.types.al.name': 'AL Amyloidosis',
    'about.types.al.description': 'Most common form, affects heart, kidneys, liver, and nervous system',
    'about.types.al.prevalence': '70% of cases',
    'about.types.aa.name': 'AA Amyloidosis',
    'about.types.aa.description': 'Secondary to chronic inflammatory conditions',
    'about.types.aa.prevalence': '20% of cases',
    'about.types.hereditary.name': 'Hereditary',
    'about.types.hereditary.description': 'Genetic forms including TTR, fibrinogen, and lysozyme',
    'about.types.hereditary.prevalence': '5% of cases',
    'about.types.other.name': 'Other Types',
    'about.types.other.description': 'Including β2-microglobulin and localized forms',
    'about.types.other.prevalence': '5% of cases',
    'about.stats.diagnosisTime': '2-3 years',
    'about.stats.diagnosisTimeLabel': 'Average time to diagnosis',
    'about.stats.diagnosisTimeDesc': 'Many patients see multiple doctors before receiving proper diagnosis',
    'about.stats.canadiansAffected': '3,000+',
    'about.stats.canadiansAffectedLabel': 'Canadians affected',
    'about.stats.canadiansAffectedDesc': 'Estimated number of people living with amyloidosis in Canada',
    
    // Events & Newsletter Section
    'events.badge': 'Stay Connected',
    'events.title.events': 'Events',
    'events.title.newsletter': '& Newsletter',
    'events.subtitle': 'Stay informed about the latest research, treatment advances, and community events in amyloidosis care.',
    'events.description': 'Join our community to receive regular updates, educational content, and information about upcoming events, webinars, and support group meetings.',
    'events.upcomingEvents': 'Upcoming Events',
    'events.latestNews': 'Latest News & Updates',
    'events.emailPlaceholder': 'Enter your email address',
    'events.subscribe': 'Subscribe to Newsletter',
    'events.stayConnected': 'Stay Connected',
    'events.joinCommunity': 'Join Our Community',
    'events.joinCommunityDesc': 'Get exclusive access to research updates, community events, and expert insights delivered monthly.',
    'events.joinMembers': 'Join 5,000+ community members',
    'events.stats.subscribers': 'Subscribers',
    'events.stats.eventsYear': 'Events/Year',
    'events.stats.provinces': 'Provinces',
    'events.stats.satisfaction': 'Satisfaction',
    'events.communityCalendar': 'Community Calendar',
    'events.communityCalendarDesc': 'Connect with experts, patients, and researchers through our comprehensive event program.',
    
    // Directory Section
    'directory.badge': 'Find Care',
    'directory.title.find': 'Find',
    'directory.title.specialized': 'Specialized Care',
    'directory.subtitle': 'Connecting healthcare across the nation',
    'directory.networkReach': 'Network Reach',
    'directory.healthcareProviders': 'Healthcare Providers',
    'directory.provincesAndTerritories': 'Provinces & Territories',
    'directory.majorCities': 'Major Cities',
    'directory.resourcesAvailable': 'Resources Available',
    'directory.browseDirectory': 'Browse Directory',
    'directory.searchableDirectory': 'Searchable Healthcare Directory',
    'directory.searchableDescription': 'Find specialized amyloidosis treatment centers, experienced physicians, and clinical experts across all Canadian provinces and territories.',
    'directory.exploreDirectory': 'Explore Full Directory',
    'directory.liveStats': 'Live Stats',
    'directory.directoryInsights': 'Directory Insights',
    'directory.needHelp': 'Need Help Finding Care?',
    'directory.nationalNetwork': 'National Network',
    'directory.canadaWide': 'Canada-Wide Coverage',
    'directory.connectingHealthcare': 'Connecting healthcare across the nation',
    
    // Quick Links Section
    'quickLinks.badge': 'Quick Access',
    'quickLinks.title.essential': 'Essential',
    'quickLinks.title.resources': 'Resources',
    'quickLinks.subtitle': 'Quick access to the most important tools and information for patients, families, and healthcare professionals.',
    'quickLinks.patientResources': 'Patient Resources',
    'quickLinks.patientResourcesDesc': 'Comprehensive guides for patients and families',
    'quickLinks.getAccess': 'Get Access',
    'quickLinks.healthcareDirectory': 'Healthcare Directory',
    'quickLinks.healthcareDirectoryDesc': 'Specialized centers and experts',
    'quickLinks.browse': 'Browse',
    'quickLinks.supportGroups': 'Support Groups',
    'quickLinks.supportGroupsDesc': 'Connect with others and find support',
    'quickLinks.connect': 'Connect',
    'quickLinks.researchUpdates': 'Research Updates',
    'quickLinks.researchUpdatesDesc': 'Latest advances and research',
    'quickLinks.stayInformed': 'Stay Informed',
    'quickLinks.emergencyContacts': 'Emergency Contacts',
    'quickLinks.emergencyContactsDesc': 'Urgent help resources',
    'quickLinks.getHelp': 'Get Help',
    'quickLinks.clinicalTrials': 'Clinical Trials',
    'quickLinks.clinicalTrialsDesc': 'Research participation opportunities',
    'quickLinks.explore': 'Explore',
    
    // Featured Spotlights Section
    'spotlights.badge': 'Featured',
    'spotlights.title.featured': 'Featured',
    'spotlights.title.spotlights': 'Spotlights',
    'spotlights.subtitle': 'Latest updates, success stories, and amyloidosis research breakthroughs from our community.',
    'spotlights.latestNews': 'Latest News',
    'spotlights.patientStories': 'Patient Stories',
    'spotlights.researchUpdates': 'Research Updates',
    'spotlights.readMore': 'Read More',
    'spotlights.viewAll': 'View All',
    'spotlights.author': 'Author',
    'spotlights.date': 'Date',
    'spotlights.category': 'Category',
    'spotlights.shareStory': 'Share Story',
    'spotlights.newsUpdates': 'News Updates',
    'spotlights.researchHighlights': 'Research Highlights',
    'spotlights.communityNews': 'Community News',
    'spotlights.patientJourney': 'Patient Journey',
    'spotlights.treatmentBreakthrough': 'Treatment Breakthrough',
    'spotlights.diagnosticImprovement': 'Diagnostic Improvement',
    
    // About Page
    'about.hero.badge': 'About CAS',
    'about.hero.title': 'Canadian Amyloidosis Society',
    'about.hero.title.connecting': 'Connecting',
    'about.hero.title.healthcare': 'Healthcare',
    'about.hero.title.canada': 'Across Canada',
    'about.hero.subtitle': 'Building a national platform for clinical practice support',
    'about.hero.description': 'Founded by healthcare professionals for healthcare professionals. We unite clinicians, researchers, and institutions to advance amyloidosis care through evidence-based collaboration.',
    'about.hero.ourMission': 'Our Mission',
    'about.hero.getInvolved': 'Get Involved',
    'about.hero.stats.professionals': 'Healthcare Professionals',
    'about.hero.stats.institutions': 'Partner Institutions',
    'about.hero.stats.resources': 'Clinical Resources',
    'about.hero.stats.provinces': 'Provinces/Territories',
    'about.whatWeDo.title': 'What We Do',
    'about.whatWeDo.toolCuration.title': 'Tool Curation',
    'about.whatWeDo.toolCuration.description': 'Evidence-based clinical tools, protocols, and diagnostic pathways developed by practicing specialists.',
    'about.whatWeDo.diagnosticSupport.title': 'Diagnostic Support',
    'about.whatWeDo.diagnosticSupport.description': 'Rapid diagnostic pathways, decision support tools, and consultation networks for complex cases.',
    'about.whatWeDo.peerLearning.title': 'Peer Learning',
    'about.whatWeDo.peerLearning.description': 'Collaborative professional networks, case discussions, and continuous medical education opportunities.',
    'about.values.patientCentered.title': 'Patient-Centered',
    'about.values.patientCentered.description': 'Every decision and resource is designed with patient outcomes as the primary focus.',
    'about.values.collaborative.title': 'Collaborative',
    'about.values.collaborative.description': 'We bring together diverse expertise to solve complex clinical challenges.',
    'about.values.evidenceInformed.title': 'Evidence-Informed',
    'about.values.evidenceInformed.description': 'All resources are grounded in current research and clinical best practices.',
    'about.values.transparent.title': 'Transparent',
    'about.values.transparent.description': 'Open access to information, clear governance, and accountable stewardship.',
    'about.services.directory': 'Comprehensive healthcare provider directory',
    'about.services.diagnosis': 'Rapid diagnostic pathway tools',
    'about.services.information': 'Clinical information resources',
    'about.services.resources': 'Professional development materials',
    'about.services.committee': 'Expert committee guidance',
    'about.committee.title': 'Executive Committee',
    'about.committee.subtitle': 'Leading healthcare professionals dedicated to advancing amyloidosis care',
    'about.committee.joinCta.title': 'Join Our Clinical Network',
    'about.committee.joinCta.subtitle': 'Contribute to advancing amyloidosis care in Canada',
    'about.committee.joinCta.description': 'Whether you\'re a clinician, researcher, or healthcare professional, there are multiple ways to contribute to our mission.',
    'about.committee.joinCta.clinician.title': 'Clinician Contributors',
    'about.committee.joinCta.clinician.description': 'Share expertise through case studies, tool validation, and peer review.',
    'about.committee.joinCta.researcher.title': 'Research Collaborators',
    'about.committee.joinCta.researcher.description': 'Contribute to evidence base through studies, publications, and data sharing.',
    'about.committee.joinCta.institutional.title': 'Institutional Partners',
    'about.committee.joinCta.institutional.description': 'Healthcare organizations supporting infrastructure and resources.',
    'about.governance.title': 'Governance & Documents',
    'about.governance.subtitle': 'Transparent governance and organizational documents',
    'about.governance.corporate.title': 'Corporate Governance',
    'about.governance.corporate.description': 'Articles of incorporation, by-laws, and board meeting minutes.',
    'about.governance.financial.title': 'Financial Transparency',
    'about.governance.financial.description': 'Annual financial reports, audited statements, and funding sources.',
    'about.governance.clinical.title': 'Clinical Governance',
    'about.governance.clinical.description': 'Evidence review processes, clinical advisory guidelines, and quality standards.',
    'about.partnerships.title': 'Strategic Partnerships',
    'about.partnerships.subtitle': 'Collaborative relationships that strengthen our impact',
    'about.partnerships.description': 'We work with leading organizations to advance amyloidosis care, research, and patient support across Canada and internationally.',
    'about.partnerships.contactUs': 'Contact Us',
    'about.partnerships.learnMore': 'Learn More',
    'about.partnerships.viewAll': 'View All Partnerships',
    'about.joinNetwork': 'Join Our Network',
    'about.getInvolved': 'Get Involved',
    'about.exploreResources': 'Explore Resources',
    'about.downloadDocument': 'Download Document',
    'about.viewDocument': 'View Document',

    // Contact Page
    'contact.hero.title': 'Contact Us',
    'contact.hero.subtitle': 'Get in touch with our team',
    'contact.hero.description': 'We\'re here to help with your questions, resource needs, and collaboration opportunities.',
    'contact.quickContact.title': 'Quick Contact',
    'contact.quickContact.generalInquiries': 'General Inquiries',
    'contact.quickContact.generalInquiries.email': 'info@canadianamyloidosis.ca',
    'contact.quickContact.generalInquiries.description': 'General questions about CAS, membership, and services',
    'contact.quickContact.generalInquiries.responseTime': '24-48 hours',
    'contact.quickContact.resourceSupport': 'Resource Support',
    'contact.quickContact.resourceSupport.email': 'resources@canadianamyloidosis.ca',
    'contact.quickContact.resourceSupport.description': 'Help with accessing or contributing clinical resources',
    'contact.quickContact.resourceSupport.responseTime': '1-2 business days',
    'contact.quickContact.patientSupport': 'Patient Support',
    'contact.quickContact.patientSupport.email': 'support@canadianamyloidosis.ca',
    'contact.quickContact.patientSupport.description': 'Patient and family support questions',
    'contact.quickContact.patientSupport.responseTime': '24-48 hours',
    'contact.quickContact.professionalInquiries': 'Professional Inquiries',
    'contact.quickContact.professionalInquiries.email': 'professionals@canadianamyloidosis.ca',
    'contact.quickContact.professionalInquiries.description': 'Healthcare provider and researcher collaboration',
    'contact.quickContact.professionalInquiries.responseTime': '3-5 business days',
    'contact.contactForm.title': 'Send us a Message',
    'contact.contactForm.subtitle': 'Fill out the form below and we\'ll get back to you promptly',
    'contact.form.name': 'Name',
    'contact.form.email': 'Email',
    'contact.form.organization': 'Organization (Optional)',
    'contact.form.inquiryType': 'Inquiry Type',
    'contact.form.subject': 'Subject',
    'contact.form.message': 'Message',
    'contact.form.privacyConsent': 'I agree to the privacy policy and terms of service',
    'contact.form.captcha': 'Security Verification',
    'contact.form.inquiryTypes.general': 'General Question',
    'contact.form.inquiryTypes.resource': 'Resource Request',
    'contact.form.inquiryTypes.support': 'Support Needed',
    'contact.form.inquiryTypes.professional': 'Professional Collaboration',
    'contact.form.inquiryTypes.media': 'Media Inquiry',
    'contact.form.inquiryTypes.other': 'Other',
    'contact.form.submit': 'Send Message',
    'contact.form.submitting': 'Sending...',
    'contact.faq.title': 'Frequently Asked Questions',
    'contact.faq.subtitle': 'Quick answers to common questions',
    'contact.faq.questions.resources.question': 'How can I access clinical resources?',
    'contact.faq.questions.resources.answer': 'Healthcare professionals can access our clinical resources through the Resources section. Some materials require registration to ensure appropriate use in clinical settings.',
    'contact.faq.questions.membership.question': 'Is there a membership fee for CAS?',
    'contact.faq.questions.membership.answer': 'CAS membership is free for all healthcare professionals and researchers. Patient and family access to support resources is also provided at no cost.',
    'contact.faq.questions.support.question': 'Do you provide direct patient care?',
    'contact.faq.questions.support.answer': 'CAS does not provide direct patient care. We connect patients with specialized healthcare providers and provide educational resources to support informed healthcare decisions.',
    'contact.faq.questions.collaboration.question': 'How can my organization partner with CAS?',
    'contact.faq.questions.collaboration.answer': 'We welcome partnerships with healthcare institutions, research organizations, and professional societies. Contact us at professionals@canadianamyloidosis.ca to discuss collaboration opportunities.',
    'contact.faq.questions.resources.contribute.question': 'Can I contribute clinical resources to CAS?',
    'contact.faq.questions.resources.contribute.answer': 'Yes! We encourage healthcare professionals to share evidence-based resources. All submissions undergo peer review to ensure clinical accuracy and relevance.',
    'contact.faq.questions.updates.question': 'How do I stay updated on CAS activities?',
    'contact.faq.questions.updates.answer': 'Join our newsletter, follow our social media channels, or register for our professional network to receive regular updates on research, resources, and events.',
    'contact.office.title': 'Office Information',
    'contact.office.address': 'National Office',
    'contact.office.addressLine1': 'Canadian Amyloidosis Society',
    'contact.office.addressLine2': 'Canada',
    'contact.office.phone': 'Phone: (555) 123-4567',
    'contact.office.email': 'Email: info@canadianamyloidosis.ca',
    'contact.office.hours': 'Office Hours',
    'contact.office.hours.weekdays': 'Monday - Friday: 9:00 AM - 5:00 PM EST',
    'contact.office.hours.weekends': 'Saturday - Sunday: Closed',
    'contact.emergencyNote': 'For medical emergencies, please contact your healthcare provider or call 911',
    'contact.languageNote': 'Services available in English and French',
    'contact.responseTime': 'Response Time',

    // Directory Page
    'directory.hero.title': 'Healthcare Directory',
    'directory.hero.subtitle': 'Find specialized amyloidosis care across Canada',
    'directory.hero.description': 'Connect with healthcare providers, treatment centers, and clinical experts experienced in amyloidosis diagnosis and care.',
    'directory.search.placeholder': 'Search by provider name, location, or specialty...',
    'directory.search.button': 'Search',
    'directory.filters.province': 'Province/Territory',
    'directory.filters.programType': 'Program Type',
    'directory.filters.viewMode': 'View Mode',
    'directory.filters.listView': 'List View',
    'directory.filters.mapView': 'Map View',
    'directory.filters.clearAll': 'Clear All',
    'directory.results.showing': 'Showing',
    'directory.results.of': 'of',
    'directory.results.centers': 'centers',
    'directory.results.noResults': 'No results found',
    'directory.results.tryDifferent': 'Try a different search or filter',
    'directory.center.viewDetails': 'View Details',
    'directory.center.getDirections': 'Get Directions',
    'directory.center.contact': 'Contact',
    'directory.center.phone': 'Phone',
    'directory.center.email': 'Email',
    'directory.center.website': 'Website',
    'directory.center.services': 'Services',
    'directory.center.specialties': 'Specialties',
    'directory.map.title': 'Healthcare Centers Map',
    'directory.map.subtitle': 'Interactive map of amyloidosis treatment centers across Canada',
    'directory.map.legend.title': 'Center Types',
    'directory.map.legend.hospital': 'Hospitals',
    'directory.map.legend.specialty': 'Specialty Centers',
    'directory.map.legend.research': 'Research Centers',
    'directory.map.legend.clinic': 'Clinics',
    'directory.stats.title': 'Network Statistics',
    'directory.stats.centers': 'Healthcare Centers',
    'directory.stats.provinces': 'Provinces & Territories',
    'directory.stats.specialists': 'Specialists',
    'directory.stats.programs': 'Programs',

    // Resources Page
    'resources.hero.title': 'Clinical Resources',
    'resources.hero.subtitle': 'Evidence-based tools for healthcare professionals',
    'resources.hero.description': 'Access comprehensive clinical resources, diagnostic tools, and educational materials developed by amyloidosis specialists.',
    'resources.types.all': 'All Types',
    'resources.types.al': 'AL Amyloidosis',
    'resources.types.attr': 'ATTR Amyloidosis',
    'resources.types.aa': 'AA Amyloidosis',
    'resources.types.alect2': 'ALect2 Amyloidosis',
    'resources.types.general': 'General Amyloidosis',
    'resources.filters.search': 'Search resources...',
    'resources.filters.amyloidosisType': 'Amyloidosis Type',
    'resources.filters.resourceType': 'Resource Type',
    'resources.filters.category': 'Category',
    'resources.filters.audience': 'Audience',
    'resources.filters.language': 'Language',
    'resources.filters.region': 'Region',
    'resources.filters.clearAll': 'Clear All',
    'resources.results.showing': 'Showing',
    'resources.results.of': 'of',
    'resources.results.resources': 'resources',
    'resources.results.noResults': 'No resources found',
    'resources.results.tryDifferent': 'Try adjusting your search criteria',
    'resources.card.download': 'Download',
    'resources.card.view': 'View',
    'resources.card.downloads': 'downloads',
    'resources.card.updated': 'Updated',
    'resources.card.category': 'Category',
    'resources.card.audience': 'Audience',
    'resources.card.language': 'Language',
    'resources.upload.title': 'Upload Resource',
    'resources.upload.description': 'Share your clinical resources with the community',
    'resources.upload.button': 'Upload Resource',

    // JoinCAS Page
    'joinCAS.hero.title': 'Join CAS',
    'joinCAS.hero.subtitle': 'Become part of Canada\'s leading amyloidosis society',
    'joinCAS.hero.description': 'Join healthcare professionals, researchers, and advocates dedicated to advancing amyloidosis care across Canada.',
    'joinCAS.form.firstName': 'First Name',
    'joinCAS.form.lastName': 'Last Name',
    'joinCAS.form.email': 'Email Address',
    'joinCAS.form.phone': 'Phone Number',
    'joinCAS.form.city': 'City',
    'joinCAS.form.province': 'Province',
    'joinCAS.form.role': 'Role',
    'joinCAS.form.specialty': 'Specialty (Optional)',
    'joinCAS.form.organization': 'Organization (Optional)',
    'joinCAS.form.interests': 'Areas of Interest',
    'joinCAS.form.howHeard': 'How did you hear about CAS?',
    'joinCAS.form.message': 'Message (Optional)',
    'joinCAS.form.newsletter': 'Subscribe to newsletter',
    'joinCAS.form.termsOfParticipation': 'I accept the Terms of Participation',
    'joinCAS.form.privacyPolicy': 'I accept the Privacy Policy',
    'joinCAS.form.submit': 'Submit Application',
    'joinCAS.form.submitting': 'Submitting...',
    'joinCAS.benefits.title': 'Membership Benefits',
    'joinCAS.benefits.subtitle': 'What you get as a CAS member',
    'joinCAS.benefits.access': 'Access to clinical resources',
    'joinCAS.benefits.networking': 'Professional networking opportunities',
    'joinCAS.benefits.education': 'Continuing education programs',
    'joinCAS.benefits.advocacy': 'Voice in healthcare policy',
    'joinCAS.benefits.research': 'Research collaboration opportunities',
    'joinCAS.benefits.support': 'Patient and family support resources',

    // Accessibility Statement Page
    'accessibility.hero.title': 'Accessibility Statement',
    'accessibility.hero.subtitle': 'Our commitment to inclusive digital experiences',
    'accessibility.hero.description': 'We are committed to ensuring our website is accessible to all users, including those with disabilities.',
    'accessibility.wcag.title': 'WCAG 2.1 Level AA Compliance',
    'accessibility.wcag.subtitle': 'We follow the Web Content Accessibility Guidelines',
    'accessibility.wcag.perceivable': 'Perceivable',
    'accessibility.wcag.operable': 'Operable',
    'accessibility.wcag.understandable': 'Understandable',
    'accessibility.wcag.robust': 'Robust',
    'accessibility.features.title': 'Accessibility Features',
    'accessibility.features.subtitle': 'Built-in accessibility tools and features',
    'accessibility.features.keyboardNavigation': 'Keyboard Navigation',
    'accessibility.features.screenReader': 'Screen Reader Support',
    'accessibility.features.highContrast': 'High Contrast Mode',
    'accessibility.features.textResize': 'Text Resize Options',
    'accessibility.features.reducedMotion': 'Reduced Motion Support',
    'accessibility.features.alternativeText': 'Alternative Text for Images',
    'accessibility.contact.title': 'Accessibility Support',
    'accessibility.contact.subtitle': 'Get help with accessibility issues',
    'accessibility.contact.description': 'If you experience any accessibility barriers, please contact us.',
    'accessibility.contact.email': 'Email: accessibility@canadianamyloidosis.ca',
    'accessibility.contact.phone': 'Phone: (555) 123-4567',
    'accessibility.contact.response': 'We aim to respond within 2 business days',
    'accessibility.lastUpdated': 'Last Updated',
    'accessibility.reviewDate': 'Next Review Date',

    // Footer
    'footer.aboutUs': 'About Us',
    'footer.ourMission': 'Our Mission',
    'footer.boardOfDirectors': 'Board of Directors',
    'footer.annualReports': 'Annual Reports',
    'footer.resources': 'Resources',
    'footer.patientResources': 'Patient Resources',
    'footer.educationalMaterials': 'Educational Materials',
    'footer.researchLibrary': 'Research Library',
    'footer.support': 'Support',
    'footer.supportGroups': 'Support Groups',
    'footer.events': 'Events',
    'footer.newsletter': 'Newsletter',
    'footer.getInvolved': 'Get Involved',
    'footer.contact': 'Contact',
    'footer.getHelp': 'Get Help',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.copyright': '© 2025 Canadian Amyloidosis Society. All rights reserved.',
    'footer.registeredCharity': 'Registered Charity #123456789RR0001'
  },
  fr: {
    // Navigation
    'nav.home': 'Accueil',
    'nav.about': 'À propos',
    'nav.resources': 'Ressources',
    'nav.directory': 'Répertoire',
    'nav.community': 'Communauté',
    'nav.contact': 'Contact',
    'nav.getHelp': 'Obtenir de l\'aide',
    
    // Hero Section
    'hero.badge': 'Plateforme d\'Excellence Clinique',
    'hero.title.canadian': 'Société',
    'hero.title.amyloidosis': 'Canadienne',
    'hero.title.society': 'd\'Amylose',
    'hero.subtitle': 'Faire progresser les soins d\'amylose fondés sur des preuves grâce à l\'excellence clinique, la collaboration professionnelle et le partage structuré des connaissances.',
    'hero.getStarted': 'Commencer',
    'hero.learnMore': 'En savoir plus',
    
    // Welcome Section
    'welcome.badge': 'Qui nous sommes',
    'welcome.title.welcome': 'Bienvenue à la',
    'welcome.title.cas': 'Société Canadienne d\'Amylose',
    'welcome.subtitle': 'Votre partenaire de confiance en soins d\'amylose, connectant patients, familles et professionnels de la santé à travers le Canada.',
    'welcome.description': 'Nous nous consacrons à améliorer la vie de ceux touchés par l\'amylose par l\'éducation, le soutien et l\'advocacy. Notre plateforme complète fournit des ressources essentielles, vous connecte avec des soins spécialisés et construit une communauté de soutien pour les patients et familles à travers le pays.',
    'welcome.mission': 'Notre Mission',
    'welcome.missionText': 'Accélérer la sensibilisation, améliorer le diagnostic et optimiser les soins pour les patients atteints d\'amylose à travers le Canada par l\'éducation, l\'advocacy et le soutien communautaire.',
    'welcome.vision': 'Notre Vision',
    'welcome.visionText': 'Un avenir où chaque Canadien touché par l\'amylose reçoit un diagnostic précoce, un traitement optimal et un soutien complet.',
    'welcome.exploreResources': 'En savoir plus sur notre travail',
    
    // About Amyloidosis Section
    'about.badge': 'Information Médicale',
    'about.title.what': 'Qu\'est-ce que l\'',
    'about.title.amyloidosis': 'Amylose',
    'about.subtitle': 'L\'amylose est une maladie rare aux conséquences qui changent la vie—mais une détection précoce peut considérablement améliorer les résultats. La Société Canadienne d\'Amylose construit un hub national de confiance pour les cliniciens, chercheurs et familles cherchant des réponses.',
    'about.description': 'L\'amylose est une condition rare mais sérieuse où des protéines mal repliées (amyloïde) s\'accumulent dans les organes et tissus à travers le corps. Comprendre les différents types, reconnaître les symptômes précoces et accéder aux soins spécialisés sont cruciaux pour gérer cette condition efficacement.',
    'about.earlyDetection': 'La Détection Précoce Sauve des Vies',
    'about.earlyDetectionText': 'Reconnaître les symptômes tôt et obtenir un diagnostic approprié peut significativement améliorer les résultats de traitement et la qualité de vie.',
    'about.earlyDetection.title': 'Détection Précoce',
    'about.earlyDetection.subtitle': 'Sauve des Vies',
    'about.earlyDetection.description': 'L\'amylose est souvent mal diagnostiquée ou diagnostiquée tardivement car ses symptômes imitent d\'autres conditions. La reconnaissance précoce et les tests appropriés sont cruciaux pour de meilleurs résultats patients.',
    'about.earlyDetection.subdescription': 'Notre répertoire connecte les patients avec des centres spécialisés et des fournisseurs de soins de santé expérimentés dans le diagnostic et le traitement de l\'amylose à travers le Canada.',
    'about.learnMore': 'En savoir plus',
    'about.types.al.name': 'Amylose AL',
    'about.types.al.description': 'Forme la plus commune, affecte le cœur, les reins, le foie et le système nerveux',
    'about.types.al.prevalence': '70% des cas',
    'about.types.aa.name': 'Amylose AA',
    'about.types.aa.description': 'Secondaire aux conditions inflammatoires chroniques',
    'about.types.aa.prevalence': '20% des cas',
    'about.types.hereditary.name': 'Héréditaire',
    'about.types.hereditary.description': 'Formes génétiques incluant TTR, fibrinogène et lysozyme',
    'about.types.hereditary.prevalence': '5% des cas',
    'about.types.other.name': 'Autres Types',
    'about.types.other.description': 'Incluant β2-microglobuline et formes localisées',
    'about.types.other.prevalence': '5% des cas',
    'about.stats.diagnosisTime': '2-3 ans',
    'about.stats.diagnosisTimeLabel': 'Temps moyen pour le diagnostic',
    'about.stats.diagnosisTimeDesc': 'Beaucoup de patients voient plusieurs médecins avant de recevoir un diagnostic approprié',
    'about.stats.canadiansAffected': '3 000+',
    'about.stats.canadiansAffectedLabel': 'Canadiens affectés',
    'about.stats.canadiansAffectedDesc': 'Nombre estimé de personnes vivant avec l\'amylose au Canada',
    
    // Events & Newsletter Section
    'events.badge': 'Restez Connectés',
    'events.title.events': 'Événements',
    'events.title.newsletter': 'et Bulletin',
    'events.subtitle': 'Restez informés sur les dernières recherches, avancées de traitement et événements communautaires en soins d\'amylose.',
    'events.description': 'Rejoignez notre communauté pour recevoir des mises à jour régulières, du contenu éducatif et des informations sur les événements à venir, webinaires et réunions de groupes de soutien.',
    'events.upcomingEvents': 'Événements à Venir',
    'events.latestNews': 'Dernières Nouvelles et Mises à Jour',
    'events.emailPlaceholder': 'Entrez votre adresse courriel',
    'events.subscribe': 'S\'abonner au Bulletin',
    'events.stayConnected': 'Restez Connectés',
    'events.joinCommunity': 'Rejoignez Notre Communauté',
    'events.joinCommunityDesc': 'Obtenez un accès exclusif aux mises à jour de recherche, événements communautaires et perspectives d\'experts livrées mensuellement.',
    'events.joinMembers': 'Rejoignez plus de 5 000 membres de la communauté',
    'events.stats.subscribers': 'Abonnés',
    'events.stats.eventsYear': 'Événements/An',
    'events.stats.provinces': 'Provinces',
    'events.stats.satisfaction': 'Satisfaction',
    'events.communityCalendar': 'Calendrier Communautaire',
    'events.communityCalendarDesc': 'Connectez-vous avec des experts, patients et chercheurs à travers notre programme d\'événements compréhensif.',
    
    // Directory Section
    'directory.badge': 'Trouver des Soins',
    'directory.title.find': 'Trouver',
    'directory.title.specialized': 'des Soins Spécialisés',
    'directory.subtitle': 'Connecter les soins de santé à travers la nation',
    'directory.networkReach': 'Portée du Réseau',
    'directory.healthcareProviders': 'Fournisseurs de Soins de Santé',
    'directory.provincesAndTerritories': 'Provinces et Territoires',
    'directory.majorCities': 'Grandes Villes',
    'directory.resourcesAvailable': 'Ressources Disponibles',
    'directory.browseDirectory': 'Parcourir le Répertoire',
    'directory.searchableDirectory': 'Répertoire de Soins de Santé Recherchable',
    'directory.searchableDescription': 'Trouvez des centres de traitement d\'amylose spécialisés, médecins expérimentés et experts cliniques dans toutes les provinces et territoires canadiens.',
    'directory.exploreDirectory': 'Explorer le Répertoire Complet',
    'directory.liveStats': 'Statistiques en Direct',
    'directory.directoryInsights': 'Perspectives du Répertoire',
    'directory.needHelp': 'Besoin d\'Aide pour Trouver des Soins?',
    'directory.nationalNetwork': 'Réseau National',
    'directory.canadaWide': 'Couverture Pancanadienne',
    'directory.connectingHealthcare': 'Connecter les soins de santé à travers la nation',
    
    // Quick Links Section
    'quickLinks.badge': 'Accès Rapide',
    'quickLinks.title.essential': 'Ressources',
    'quickLinks.title.resources': 'Essentielles',
    'quickLinks.subtitle': 'Accès rapide aux outils et informations les plus importantes pour les patients, familles et professionnels de la santé.',
    'quickLinks.patientResources': 'Ressources pour Patients',
    'quickLinks.patientResourcesDesc': 'Guides complets pour patients et familles',
    'quickLinks.getAccess': 'Obtenir l\'Accès',
    'quickLinks.healthcareDirectory': 'Répertoire de Soins de Santé',
    'quickLinks.healthcareDirectoryDesc': 'Centres spécialisés et experts',
    'quickLinks.browse': 'Parcourir',
    'quickLinks.supportGroups': 'Groupes de Soutien',
    'quickLinks.supportGroupsDesc': 'Connectez-vous avec d\'autres et trouvez du soutien',
    'quickLinks.connect': 'Connecter',
    'quickLinks.researchUpdates': 'Mises à Jour de Recherche',
    'quickLinks.researchUpdatesDesc': 'Dernières avancées et recherches',
    'quickLinks.stayInformed': 'Rester Informé',
    'quickLinks.emergencyContacts': 'Contacts d\'Urgence',
    'quickLinks.emergencyContactsDesc': 'Ressources d\'aide urgente',
    'quickLinks.getHelp': 'Obtenir de l\'Aide',
    'quickLinks.clinicalTrials': 'Essais Cliniques',
    'quickLinks.clinicalTrialsDesc': 'Opportunités de participation à la recherche',
    'quickLinks.explore': 'Explorer',
    
    // Featured Spotlights Section
    'spotlights.badge': 'En Vedette',
    'spotlights.title.featured': 'En',
    'spotlights.title.spotlights': 'Vedette',
    'spotlights.subtitle': 'Dernières mises à jour, histoires de réussite et percées de recherche en amylose de notre communauté.',
    'spotlights.latestNews': 'Dernières Nouvelles',
    'spotlights.patientStories': 'Histoires de Patients',
    'spotlights.researchUpdates': 'Mises à Jour de Recherche',
    'spotlights.readMore': 'Lire Plus',
    'spotlights.viewAll': 'Voir Tout',
    'spotlights.author': 'Auteur',
    'spotlights.date': 'Date',
    'spotlights.category': 'Catégorie',
    'spotlights.shareStory': 'Partager l\'Histoire',
    'spotlights.newsUpdates': 'Mises à Jour de Nouvelles',
    'spotlights.researchHighlights': 'Points Saillants de la Recherche',
    'spotlights.communityNews': 'Nouvelles de la Communauté',
    'spotlights.patientJourney': 'Parcours du Patient',
    'spotlights.treatmentBreakthrough': 'Percée de Traitement',
    'spotlights.diagnosticImprovement': 'Amélioration Diagnostique',
    
    // About Page
    'about.hero.badge': 'À Propos de SCA',
    'about.hero.title': 'Société Canadienne d\'Amylose',
    'about.hero.subtitle': 'Construire une plateforme nationale pour le soutien de la pratique clinique',
    'about.hero.description': 'Fondée par des professionnels de la santé pour des professionnels de la santé. Nous unissons cliniciens, chercheurs et institutions pour faire progresser les soins d\'amylose grâce à la collaboration fondée sur des preuves.',
    'about.hero.stats.professionals': 'Professionnels de la Santé',
    'about.hero.stats.institutions': 'Institutions Partenaires',
    'about.hero.stats.resources': 'Ressources Cliniques',
    'about.hero.stats.provinces': 'Provinces/Territoires',
    'about.whatWeDo.title': 'Ce Que Nous Faisons',
    'about.whatWeDo.toolCuration.title': 'Curation d\'Outils',
    'about.whatWeDo.toolCuration.description': 'Outils cliniques fondés sur des preuves, protocoles et voies diagnostiques développés par des spécialistes praticiens.',
    'about.whatWeDo.diagnosticSupport.title': 'Soutien Diagnostique',
    'about.whatWeDo.diagnosticSupport.description': 'Voies diagnostiques rapides, outils d\'aide à la décision et réseaux de consultation pour les cas complexes.',
    'about.whatWeDo.peerLearning.title': 'Apprentissage entre Pairs',
    'about.whatWeDo.peerLearning.description': 'Réseaux professionnels collaboratifs, discussions de cas et opportunités de formation médicale continue.',
    'about.values.patientCentered.title': 'Centrés sur le Patient',
    'about.values.patientCentered.description': 'Chaque décision et ressource est conçue avec les résultats du patient comme objectif principal.',
    'about.values.collaborative.title': 'Collaboratif',
    'about.values.collaborative.description': 'Nous rassemblons diverses expertises pour résoudre des défis cliniques complexes.',
    'about.values.evidenceInformed.title': 'Basé sur les Preuves',
    'about.values.evidenceInformed.description': 'Toutes les ressources sont fondées sur la recherche actuelle et les meilleures pratiques cliniques.',
    'about.values.transparent.title': 'Transparent',
    'about.values.transparent.description': 'Accès libre à l\'information, gouvernance claire et gestion responsable.',
    'about.services.directory': 'Répertoire complet de fournisseurs de soins de santé',
    'about.services.diagnosis': 'Outils de voie diagnostique rapide',
    'about.services.information': 'Ressources d\'information clinique',
    'about.services.resources': 'Matériels de développement professionnel',
    'about.services.committee': 'Orientation de comité d\'experts',
    'about.committee.title': 'Comité Exécutif',
    'about.committee.subtitle': 'Professionnels de la santé leaders dédiés à l\'avancement des soins d\'amylose',
    'about.committee.joinCta.title': 'Rejoignez Notre Réseau Clinique',
    'about.committee.joinCta.subtitle': 'Contribuez à l\'avancement des soins d\'amylose au Canada',
    'about.committee.joinCta.description': 'Que vous soyez clinicien, chercheur ou professionnel de la santé, il existe plusieurs façons de contribuer à notre mission.',
    'about.committee.joinCta.clinician.title': 'Contributeurs Cliniciens',
    'about.committee.joinCta.clinician.description': 'Partagez l\'expertise à travers des études de cas, validation d\'outils et évaluation par les pairs.',
    'about.committee.joinCta.researcher.title': 'Collaborateurs de Recherche',
    'about.committee.joinCta.researcher.description': 'Contribuez à la base de preuves par des études, publications et partage de données.',
    'about.committee.joinCta.institutional.title': 'Partenaires Institutionnels',
    'about.committee.joinCta.institutional.description': 'Organisations de soins de santé soutenant l\'infrastructure et les ressources.',
    'about.governance.title': 'Gouvernance et Documents',
    'about.governance.subtitle': 'Gouvernance transparente et documents organisationnels',
    'about.governance.corporate.title': 'Gouvernance Corporative',
    'about.governance.corporate.description': 'Statuts constitutifs, règlements et procès-verbaux du conseil d\'administration.',
    'about.governance.financial.title': 'Transparence Financière',
    'about.governance.financial.description': 'Rapports financiers annuels, états audités et sources de financement.',
    'about.governance.clinical.title': 'Gouvernance Clinique',
    'about.governance.clinical.description': 'Processus de révision des preuves, directives de comité consultatif clinique et normes de qualité.',
    'about.partnerships.title': 'Partenariats Stratégiques',
    'about.partnerships.subtitle': 'Relations collaboratives qui renforcent notre impact',
    'about.partnerships.description': 'Nous travaillons avec des organisations leaders pour faire progresser les soins, la recherche et le soutien aux patients d\'amylose au Canada et à l\'international.',
    'about.partnerships.contactUs': 'Contactez-Nous',
    'about.partnerships.learnMore': 'En Savoir Plus',
    'about.partnerships.viewAll': 'Voir Tous les Partenariats',
    'about.joinNetwork': 'Rejoignez Notre Réseau',
    'about.getInvolved': 'S\'Impliquer',
    'about.exploreResources': 'Explorer les Ressources',
    'about.downloadDocument': 'Télécharger le Document',
    'about.viewDocument': 'Voir le Document',

    // Contact Page
    'contact.hero.title': 'Contactez-Nous',
    'contact.hero.subtitle': 'Entrez en contact avec notre équipe',
    'contact.hero.description': 'Nous sommes là pour vous aider avec vos questions, besoins de ressources et opportunités de collaboration.',
    'contact.quickContact.title': 'Contact Rapide',
    'contact.quickContact.generalInquiries': 'Demandes Générales',
    'contact.quickContact.generalInquiries.email': 'info@canadianamyloidosis.ca',
    'contact.quickContact.generalInquiries.description': 'Questions générales sur SCA, adhésion et services',
    'contact.quickContact.generalInquiries.responseTime': '24-48 heures',
    'contact.quickContact.resourceSupport': 'Soutien aux Ressources',
    'contact.quickContact.resourceSupport.email': 'ressources@canadianamyloidosis.ca',
    'contact.quickContact.resourceSupport.description': 'Aide pour accéder ou contribuer aux ressources cliniques',
    'contact.quickContact.resourceSupport.responseTime': '1-2 jours ouvrables',
    'contact.quickContact.patientSupport': 'Soutien aux Patients',
    'contact.quickContact.patientSupport.email': 'soutien@canadianamyloidosis.ca',
    'contact.quickContact.patientSupport.description': 'Questions de soutien aux patients et familles',
    'contact.quickContact.patientSupport.responseTime': '24-48 heures',
    'contact.quickContact.professionalInquiries': 'Demandes Professionnelles',
    'contact.quickContact.professionalInquiries.email': 'professionnels@canadianamyloidosis.ca',
    'contact.quickContact.professionalInquiries.description': 'Collaboration avec les fournisseurs de soins de santé et chercheurs',
    'contact.quickContact.professionalInquiries.responseTime': '3-5 jours ouvrables',
    'contact.contactForm.title': 'Envoyez-nous un Message',
    'contact.contactForm.subtitle': 'Remplissez le formulaire ci-dessous et nous vous répondrons rapidement',
    'contact.form.name': 'Nom',
    'contact.form.email': 'Courriel',
    'contact.form.organization': 'Organisation (Optionnel)',
    'contact.form.inquiryType': 'Type de Demande',
    'contact.form.subject': 'Sujet',
    'contact.form.message': 'Message',
    'contact.form.privacyConsent': 'J\'accepte la politique de confidentialité et les conditions d\'utilisation',
    'contact.form.captcha': 'Vérification de Sécurité',
    'contact.form.inquiryTypes.general': 'Question Générale',
    'contact.form.inquiryTypes.resource': 'Demande de Ressource',
    'contact.form.inquiryTypes.support': 'Soutien Nécessaire',
    'contact.form.inquiryTypes.professional': 'Collaboration Professionnelle',
    'contact.form.inquiryTypes.media': 'Demande Médiatique',
    'contact.form.inquiryTypes.other': 'Autre',
    'contact.form.submit': 'Envoyer le Message',
    'contact.form.submitting': 'Envoi en cours...',
    'contact.faq.title': 'Questions Fréquemment Posées',
    'contact.faq.subtitle': 'Réponses rapides aux questions courantes',
    'contact.faq.questions.resources.question': 'Comment puis-je accéder aux ressources cliniques?',
    'contact.faq.questions.resources.answer': 'Les professionnels de la santé peuvent accéder à nos ressources cliniques via la section Ressources. Certains matériels nécessitent une inscription pour assurer une utilisation appropriée en milieu clinique.',
    'contact.faq.questions.membership.question': 'Y a-t-il des frais d\'adhésion pour SCA?',
    'contact.faq.questions.membership.answer': 'L\'adhésion à SCA est gratuite pour tous les professionnels de la santé et chercheurs. L\'accès aux ressources de soutien pour patients et familles est également fourni sans frais.',
    'contact.faq.questions.support.question': 'Fournissez-vous des soins directs aux patients?',
    'contact.faq.questions.support.answer': 'SCA ne fournit pas de soins directs aux patients. Nous connectons les patients avec des fournisseurs de soins de santé spécialisés et fournissons des ressources éducatives pour soutenir des décisions de soins éclairées.',
    'contact.faq.questions.collaboration.question': 'Comment mon organisation peut-elle s\'associer avec SCA?',
    'contact.faq.questions.collaboration.answer': 'Nous accueillons les partenariats avec les institutions de soins de santé, organisations de recherche et sociétés professionnelles. Contactez-nous à professionnels@canadianamyloidosis.ca pour discuter d\'opportunités de collaboration.',
    'contact.faq.questions.resources.contribute.question': 'Puis-je contribuer des ressources cliniques à SCA?',
    'contact.faq.questions.resources.contribute.answer': 'Oui! Nous encourageons les professionnels de la santé à partager des ressources fondées sur des preuves. Toutes les soumissions subissent une évaluation par les pairs pour assurer l\'exactitude et la pertinence cliniques.',
    'contact.faq.questions.updates.question': 'Comment rester informé des activités de SCA?',
    'contact.faq.questions.updates.answer': 'Rejoignez notre bulletin, suivez nos canaux de médias sociaux, ou inscrivez-vous à notre réseau professionnel pour recevoir des mises à jour régulières sur la recherche, les ressources et les événements.',
    'contact.office.title': 'Information du Bureau',
    'contact.office.address': 'Bureau National',
    'contact.office.addressLine1': 'Société Canadienne d\'Amylose',
    'contact.office.addressLine2': 'Canada',
    'contact.office.phone': 'Téléphone: (555) 123-4567',
    'contact.office.email': 'Courriel: info@canadianamyloidosis.ca',
    'contact.office.hours': 'Heures d\'Ouverture',
    'contact.office.hours.weekdays': 'Lundi - Vendredi: 9h00 - 17h00 EST',
    'contact.office.hours.weekends': 'Samedi - Dimanche: Fermé',
    'contact.emergencyNote': 'Pour les urgences médicales, veuillez contacter votre fournisseur de soins de santé ou appeler le 911',
    'contact.languageNote': 'Services disponibles en anglais et en français',
    'contact.responseTime': 'Temps de Réponse',

    // Directory Page
    'directory.hero.title': 'Répertoire de Soins de Santé',
    'directory.hero.subtitle': 'Trouvez des soins d\'amylose spécialisés à travers le Canada',
    'directory.hero.description': 'Connectez-vous avec des fournisseurs de soins de santé, centres de traitement et experts cliniques expérimentés en diagnostic et soins d\'amylose.',
    'directory.search.placeholder': 'Rechercher par nom de fournisseur, lieu ou spécialité...',
    'directory.search.button': 'Rechercher',
    'directory.filters.province': 'Province/Territoire',
    'directory.filters.programType': 'Type de Programme',
    'directory.filters.viewMode': 'Mode de Vue',
    'directory.filters.listView': 'Vue en Liste',
    'directory.filters.mapView': 'Vue Carte',
    'directory.filters.clearAll': 'Effacer Tout',
    'directory.results.showing': 'Affichage',
    'directory.results.of': 'de',
    'directory.results.centers': 'centres',
    'directory.results.noResults': 'Aucun résultat trouvé',
    'directory.results.tryDifferent': 'Essayez une recherche ou un filtre différent',
    'directory.center.viewDetails': 'Voir les Détails',
    'directory.center.getDirections': 'Obtenir des Directions',
    'directory.center.contact': 'Contact',
    'directory.center.phone': 'Téléphone',
    'directory.center.email': 'Courriel',
    'directory.center.website': 'Site Web',
    'directory.center.services': 'Services',
    'directory.center.specialties': 'Spécialités',
    'directory.map.title': 'Carte des Centres de Soins de Santé',
    'directory.map.subtitle': 'Carte interactive des centres de traitement d\'amylose à travers le Canada',
    'directory.map.legend.title': 'Types de Centres',
    'directory.map.legend.hospital': 'Hôpitaux',
    'directory.map.legend.specialty': 'Centres Spécialisés',
    'directory.map.legend.research': 'Centres de Recherche',
    'directory.map.legend.clinic': 'Cliniques',
    'directory.stats.title': 'Statistiques du Réseau',
    'directory.stats.centers': 'Centres de Soins de Santé',
    'directory.stats.provinces': 'Provinces et Territoires',
    'directory.stats.specialists': 'Spécialistes',
    'directory.stats.programs': 'Programmes',

    // Resources Page
    'resources.hero.title': 'Ressources Cliniques',
    'resources.hero.subtitle': 'Outils fondés sur des preuves pour les professionnels de la santé',
    'resources.hero.description': 'Accédez à des ressources cliniques complètes, outils diagnostiques et matériels éducatifs développés par des spécialistes de l\'amylose.',
    'resources.types.all': 'Tous Types',
    'resources.types.al': 'Amylose AL',
    'resources.types.attr': 'Amylose ATTR',
    'resources.types.aa': 'Amylose AA',
    'resources.types.alect2': 'Amylose ALect2',
    'resources.types.general': 'Amylose Générale',
    'resources.filters.search': 'Rechercher des ressources...',
    'resources.filters.amyloidosisType': 'Type d\'Amylose',
    'resources.filters.resourceType': 'Type de Ressource',
    'resources.filters.category': 'Catégorie',
    'resources.filters.audience': 'Audience',
    'resources.filters.language': 'Langue',
    'resources.filters.region': 'Région',
    'resources.filters.clearAll': 'Effacer Tout',
    'resources.results.showing': 'Affichage',
    'resources.results.of': 'de',
    'resources.results.resources': 'ressources',
    'resources.results.noResults': 'Aucune ressource trouvée',
    'resources.results.tryDifferent': 'Essayez d\'ajuster vos critères de recherche',
    'resources.card.download': 'Télécharger',
    'resources.card.view': 'Voir',
    'resources.card.downloads': 'téléchargements',
    'resources.card.updated': 'Mis à jour',
    'resources.card.category': 'Catégorie',
    'resources.card.audience': 'Audience',
    'resources.card.language': 'Langue',
    'resources.upload.title': 'Téléverser une Ressource',
    'resources.upload.description': 'Partagez vos ressources cliniques avec la communauté',
    'resources.upload.button': 'Téléverser une Ressource',

    // JoinCAS Page
    'joinCAS.hero.title': 'Rejoindre SCA',
    'joinCAS.hero.subtitle': 'Faites partie de la société d\'amylose leader au Canada',
    'joinCAS.hero.description': 'Rejoignez des professionnels de la santé, chercheurs et défenseurs dédiés à faire progresser les soins d\'amylose à travers le Canada.',
    'joinCAS.form.firstName': 'Prénom',
    'joinCAS.form.lastName': 'Nom de famille',
    'joinCAS.form.email': 'Adresse courriel',
    'joinCAS.form.phone': 'Numéro de téléphone',
    'joinCAS.form.city': 'Ville',
    'joinCAS.form.province': 'Province',
    'joinCAS.form.role': 'Rôle',
    'joinCAS.form.specialty': 'Spécialité (Optionnel)',
    'joinCAS.form.organization': 'Organisation (Optionnel)',
    'joinCAS.form.interests': 'Domaines d\'intérêt',
    'joinCAS.form.howHeard': 'Comment avez-vous entendu parler de SCA?',
    'joinCAS.form.message': 'Message (Optionnel)',
    'joinCAS.form.newsletter': 'S\'abonner au bulletin',
    'joinCAS.form.termsOfParticipation': 'J\'accepte les Conditions de Participation',
    'joinCAS.form.privacyPolicy': 'J\'accepte la Politique de Confidentialité',
    'joinCAS.form.submit': 'Soumettre la Demande',
    'joinCAS.form.submitting': 'Soumission en cours...',
    'joinCAS.benefits.title': 'Avantages de l\'Adhésion',
    'joinCAS.benefits.subtitle': 'Ce que vous obtenez en tant que membre SCA',
    'joinCAS.benefits.access': 'Accès aux ressources cliniques',
    'joinCAS.benefits.networking': 'Opportunités de réseautage professionnel',
    'joinCAS.benefits.education': 'Programmes de formation continue',
    'joinCAS.benefits.advocacy': 'Voix dans la politique de santé',
    'joinCAS.benefits.research': 'Opportunités de collaboration de recherche',
    'joinCAS.benefits.support': 'Ressources de soutien aux patients et familles',

    // Accessibility Statement Page
    'accessibility.hero.title': 'Déclaration d\'Accessibilité',
    'accessibility.hero.subtitle': 'Notre engagement envers des expériences numériques inclusives',
    'accessibility.hero.description': 'Nous nous engageons à garantir que notre site web soit accessible à tous les utilisateurs, y compris ceux ayant des handicaps.',
    'accessibility.wcag.title': 'Conformité WCAG 2.1 Niveau AA',
    'accessibility.wcag.subtitle': 'Nous suivons les Directives pour l\'accessibilité du contenu web',
    'accessibility.wcag.perceivable': 'Perceptible',
    'accessibility.wcag.operable': 'Utilisable',
    'accessibility.wcag.understandable': 'Compréhensible',
    'accessibility.wcag.robust': 'Robuste',
    'accessibility.features.title': 'Fonctionnalités d\'Accessibilité',
    'accessibility.features.subtitle': 'Outils et fonctionnalités d\'accessibilité intégrés',
    'accessibility.features.keyboardNavigation': 'Navigation au Clavier',
    'accessibility.features.screenReader': 'Support de Lecteur d\'Écran',
    'accessibility.features.highContrast': 'Mode Haut Contraste',
    'accessibility.features.textResize': 'Options de Redimensionnement du Texte',
    'accessibility.features.reducedMotion': 'Support de Mouvement Réduit',
    'accessibility.features.alternativeText': 'Texte Alternatif pour les Images',
    'accessibility.contact.title': 'Support d\'Accessibilité',
    'accessibility.contact.subtitle': 'Obtenez de l\'aide pour les problèmes d\'accessibilité',
    'accessibility.contact.description': 'Si vous rencontrez des obstacles d\'accessibilité, veuillez nous contacter.',
    'accessibility.contact.email': 'Courriel: accessibilite@canadianamyloidosis.ca',
    'accessibility.contact.phone': 'Téléphone: (555) 123-4567',
    'accessibility.contact.response': 'Nous visons à répondre dans les 2 jours ouvrables',
    'accessibility.lastUpdated': 'Dernière mise à jour',
    'accessibility.reviewDate': 'Date de prochaine révision',

    // Footer
    'footer.aboutUs': 'À Propos de Nous',
    'footer.ourMission': 'Notre Mission',
    'footer.boardOfDirectors': 'Conseil d\'Administration',
    'footer.annualReports': 'Rapports Annuels',
    'footer.resources': 'Ressources',
    'footer.patientResources': 'Ressources pour Patients',
    'footer.educationalMaterials': 'Matériels Éducatifs',
    'footer.researchLibrary': 'Bibliothèque de Recherche',
    'footer.support': 'Soutien',
    'footer.supportGroups': 'Groupes de Soutien',
    'footer.events': 'Événements',
    'footer.newsletter': 'Bulletin',
    'footer.getInvolved': 'S\'Impliquer',
    'footer.contact': 'Contact',
    'footer.getHelp': 'Obtenir de l\'Aide',
    'footer.privacy': 'Politique de Confidentialité',
    'footer.terms': 'Conditions d\'Utilisation',
    'footer.copyright': '© 2025 Société Canadienne d\'Amylose. Tous droits réservés.',
    'footer.registeredCharity': 'Organisme de Bienfaisance Enregistré #123456789RR0001'
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  useEffect(() => {
    const savedLanguage = localStorage.getItem('language') as Language;
    if (savedLanguage && (savedLanguage === 'en' || savedLanguage === 'fr')) {
      setLanguage(savedLanguage);
    }
  }, []);

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};